port: 8000

auth:
  hash_salt: "hash_salt"
  signing_key: "signing_key"
  token_ttl: 86400

mongo:
  uri: "mongodb://mongodb:27017"
  name: "testdb"
  user_collection: "users"
  photo_collection: "photos"

photo:
  upload_dir: "/tmp/test"
  upload_allowed_types:
    - "image/jpeg"
    - "image/png"
    - "image/gif"