# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.x'

    - name: Install dependencies
      working-directory: ./API
      run: |
        go get .

    - name: Build
      working-directory: ./API
      run: go build -v ./API/cmd/api/main.go

    - name: Test
      working-directory: ./API
      run: go test -v ./API/...
    - name: Upload Go test results
      working-directory: ./API
      uses: actions/upload-artifact@v4
      with:
        name: Go-results-${{ matrix.go-version }}
        path: TestResults-${{ matrix.go-version }}.json